[toolchain]
anchor_version = "1.0.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
aargau_manager = "AargMgr1111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path=programs/aargau-manager/Cargo.toml"
